config/routes.rb
Rails.application.routes.draw do
  
  resources :proveniences
  resources :categories
  get 'orderitems/index'
  
  get 'orderitems/show'
  
  get 'orderitems/new'
   
  get 'orderitems/edit'
  

  resources :orders do 
    resources:orderitems
  end

  resources:categories
  
  devise_for :users do 
    resources :orders 
  end
  
   
  
  
  get 'cart/index'
  resources :items
  
  get '/checkout' => 'cart#createOrder'
  resources :charges
  
  
  
  root 'static_pages#home'
  get '/help' => 'static_pages#help' 
  get '/about'=> 'static_pages#about'
  get '/products'=> 'items#index'
  

  #user login routes --------------
  get '/login' => 'user#login' 
  get '/logout' => 'user#logout'

  #admin login routes -------------
   get 'admin' => 'user#login'

  #user cart routes------------------
  get '/cart/clear', to: 'cart#clearCart'
  get '/cart', to: 'cart#index'
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/decrease/:id' => 'cart#increase'
  get '/cart/increase/:id' => 'cart#decrease'
  
  #pay routes
  get '/paid/:id' => 'static_pages#paid'
  
  get '/orders/:id' => 'static_pages#orders'
  
  #categories route
  get '/category/:title', to: 'static_pages#category'
  
  #proveniences route
  get '/provenience/:title', to: 'static_pages#provenience'
  
  
  #search route
  post '/search' => 'items#search'
  
  #paypal route
  get '/thankyou/:id' => 'static_pages#thankyou'
  
    #admin related routes
  get '/upgrade/:id' => 'static_pages#upgrade'
  get '/upgrade/:id' => 'static_pages#downgrade'

  
  
  get '/allusers', to: 'static_pages#allusers'
  #homepage
  root :to => 'site#home'
  
end

app/models/provenience.rb
class Provenience < ApplicationRecord
end

app/controllers/proveniences_controller.rb
class ProveniencesController < ApplicationController
  before_action :set_provenience, only: [:show, :edit, :update, :destroy]

  # GET /proveniences
  # GET /proveniences.json
  def index
    @proveniences = Provenience.all
  end

  # GET /proveniences/1
  # GET /proveniences/1.json
  def show
  end

  # GET /proveniences/new
  def new
    @provenience = Provenience.new
  end

  # GET /proveniences/1/edit
  def edit
  end

  # POST /proveniences
  # POST /proveniences.json
  def create
    @provenience = Provenience.new(provenience_params)

    respond_to do |format|
      if @provenience.save
        format.html { redirect_to @provenience, notice: 'Provenience was successfully created.' }
        format.json { render :show, status: :created, location: @provenience }
      else
        format.html { render :new }
        format.json { render json: @provenience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proveniences/1
  # PATCH/PUT /proveniences/1.json
  def update
    respond_to do |format|
      if @provenience.update(provenience_params)
        format.html { redirect_to @provenience, notice: 'Provenience was successfully updated.' }
        format.json { render :show, status: :ok, location: @provenience }
      else
        format.html { render :edit }
        format.json { render json: @provenience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveniences/1
  # DELETE /proveniences/1.json
  def destroy
    @provenience.destroy
    respond_to do |format|
      format.html { redirect_to proveniences_url, notice: 'Provenience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provenience
      @provenience = Provenience.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def provenience_params
      params.require(:provenience).permit(:title, :description, :image)
    end
end

app/helpers/proveniences_helper.rb
module ProveniencesHelper
end

app/views/proveniences/_form.html.erb
<%= form_for(provenience) do |f| %>
  <% if provenience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(provenience.errors.count, "error") %> prohibited this provenience from being saved:</h2>

      <ul>
      <% provenience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proveniences/edit.html.erb
<h1>Editing Provenience</h1>

<%= render 'form', provenience: @provenience %>

<%= link_to 'Show', @provenience %> |
<%= link_to 'Back', proveniences_path %>

app/views/proveniences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proveniences</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proveniences.each do |provenience| %>
      <tr>
        <td><%= provenience.title %></td>
        <td><%= provenience.description %></td>
        <td><%= provenience.image %></td>
        <td><%= link_to 'Show', provenience %></td>
        <td><%= link_to 'Edit', edit_provenience_path(provenience) %></td>
        <td><%= link_to 'Destroy', provenience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provenience', new_provenience_path %>

app/views/proveniences/new.html.erb
<h1>New Provenience</h1>

<%= render 'form', provenience: @provenience %>

<%= link_to 'Back', proveniences_path %>

app/views/proveniences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @provenience.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @provenience.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @provenience.image %>
</p>

<%= link_to 'Edit', edit_provenience_path(@provenience) %> |
<%= link_to 'Back', proveniences_path %>