config/routes.rb
Rails.application.routes.draw do
  
  resources :proveniences
  resources :categories
  get 'orderitems/index'
  
  get 'orderitems/show'
  
  get 'orderitems/new'
   
  get 'orderitems/edit'
  

  resources :orders do 
    resources:orderitems
  end

  resources:categories
  
  devise_for :users do 
    resources :orders 
  end
  
   
  
  
  get 'cart/index'
  resources :items
  
  get '/checkout' => 'cart#createOrder'
  resources :charges
  
  
  
  root 'static_pages#home'
  get '/help' => 'static_pages#help' 
  get '/about'=> 'static_pages#about'
  get '/products'=> 'items#index'
  

  #user login routes --------------
  get '/login' => 'user#login' 
  get '/logout' => 'user#logout'

  #admin login routes -------------
   get 'admin' => 'user#login'

  #user cart routes------------------
  get '/cart/clear', to: 'cart#clearCart'
  get '/cart', to: 'cart#index'
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/decrease/:id' => 'cart#increase'
  get '/cart/increase/:id' => 'cart#decrease'
  
  #pay routes
  get '/paid/:id' => 'static_pages#paid'
  
  get '/orders/:id' => 'static_pages#orders'
  
  #categories route
  get '/category/:title', to: 'static_pages#category'
  
  #proveniences route
  get '/provenience/:title', to: 'static_pages#provenience'
  
  
  #search route
  post '/search' => 'items#search'
  
  #paypal route
  get '/thankyou/:id' => 'static_pages#thankyou'
  
    #admin related routes
  get '/upgrade/:id' => 'static_pages#upgrade'
  get '/upgrade/:id' => 'static_pages#downgrade'

  
  
  get '/allusers', to: 'static_pages#allusers'
  #homepage
  root :to => 'site#home'
  
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, presence: true, length: { minimum: 2, maximum: 100 }
    validates :description, presence: true, length: { minimum: 2, maximum: 100 }
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all.paginate(page: params[:page], per_page: 4)
    
    @categories = Category.all
    
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def search
     st = "%#{params[:q]}%"
     @items = Item.where("category like ?", st)
  end


  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :provenience, :inStock)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_categories.html.erb
<div class="categories">
    
    
    <h3>Categories</h3>

    
    <% @categories.each do |category| %>

<div class="list-group">
  <button type="button" class="list-group-item list-group-item-action "><p><a href="/category/<%= category.title %>" ><%= category.title %></a></p></button>

</div>
 

    <% end %>
    </div>

app/views/items/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
  <div class=" text-center">
    <small>Copyright &copy; Your Website</small>
    <% if session[:login] == 1 %>    
      
    <% end %>
  </div>
</footer>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(item.errors.count, "error") %> prevented this item from being saved:</h2>
      <ul>
      <% item.errors.full_messages.each do |message| %>
      
      <div role="alert">
        <ul>
         <li><%= message %></li>
        </ul>
      </div>
        
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <form>
      <div class="form-group row">
        <%= f.label :title, class: "col-2 col-form-label text-green" %>
        <div class="col-10">
          <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :description, class: "col-2 col-form-label text-green" %>
        <div class="col-10"> 
          <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of item" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :image_url, class: "col-2 col-form-label text-green" %>
        <div class="col-10"> 
          <%= f.text_area :image_url, class: "form-control shadow rounded", placeholder: "Image URL" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :category, class: "col-2 col-form-label text-green" %>
        <div class="col-10"> 
          <%= f.text_area :category, class: "form-control shadow rounded", placeholder: "Item category" %>
        </div>
      </div>
       <div class="form-group row ">
        <%= f.label :provenience, class: "col-2 col-form-label text-green" %>
        <div class="col-10"> 
          <%= f.text_area :provenience,  class: "form-control shadow rounded", placeholder: "Item provenience" %>
        </div>
      </div>
      <div class="form-group row  ">
        <%= f.label :price, class: "col-2 col-form-label text-green" %>
        <div class="col-10"> 
          <%= f.text_area :price,  class: "form-control shadow rounded", placeholder: "Item price" %>
        </div>
      </div>
      <div class="form-group row col-2">
        <div class="form-check ">
          <%= f.label :inStock %>
            <%= f.check_box :inStock %>
          </label>
        </div>
      </div>
      <div class="form-group row justify-content-center col-10">
        <%= f.submit class: "btn btn-outline-success btn-lg" %>
      </div>
    </form>
    </div>
<% end %>

app/views/items/_header.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-light mb-5" style="background-color: #b20000;">
  <a class="navbar-brand" href="/"><%= image_tag("food-world-logo-sm.png", alt: "Logo", :class => "logo") %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
          <%= link_to "Home", "/", class: "nav-link" %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
          <%= link_to "Help", "/help", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", "/about", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Products", "/products", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Log In", "/login", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Log Out", "/logout", class: "nav-link" %>
      </li>
      <li class="nav-item">
      <li><%= link_to "View Cart", "/cart", class: "nav-link"  %></li>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
          <%= link_to "Past Orders", "/orders/", class: "nav-link" %>
      </li>

        <li><%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: "nav-link" %></li>
      <% else %>
        <li><%= link_to 'Register', new_user_registration_path, class: "nav-link" %></li> 
        <li><%= link_to 'Sign in', new_user_session_path, class: "nav-link" %></li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <%=render 'items/search'%>
  </div>
</nav>

app/views/items/_paypalForm.html.erb
<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick">
<input type="hidden" name="business" value="company2@liammccabe.ie">
<input type="hidden" name="item_name" value="Golf Store Order Number <%= @orderNum %>">
<input type="hidden" name="currency_code" value="EUR">
<input type="hidden" name="amount" value="<%= @overall %>">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<input type="hidden" name="return" value="https://rails-container-liamme.c9users.io/" >
</form>

app/views/items/_popular.html.erb
<div class="pop-box">
  <h3>Popular Items</h3>
  <table class="catalog">
    <% @items.limit(2).order(:id).each do |item| %>
        <tr>
          <td>
            <div class="image">
              <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
            </div>
            <div class="title">
              <%= link_to item.title, item %>
            </div>
            <div class="description">
              <%= item.description %>
            </div>  
            <div class="price">
              <%= number_to_currency(item.price, :unit => "€") %>
            </div>
            <div class="links">
              <% if session[:login] ==1 %>
                <%= link_to 'Edit', edit_item_path(item) %>
                <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
              <%else%>
                <button class="btn1" onclick="window.location.href='/cart/<%= item.id %>'">
                  <span class="circle" aria-hidden="true">
                  <span class="icon arrow"></span>
                  </span>
                  <span class="button-text">Add to Cart</span>
                </button>
              <%end%>  
          </div>
          </td>
        </tr>
      <% end %>
  </table>
</div>

app/views/items/_proveniences.html.erb
<div class="proveniences">
    
    <h3>Provenience</h3>

    <div class="col-3">
    <% @proveniences.each do |provenience| %>
    
        <div class="itemhols">
            <p><%= provenience.title %></p>
            <%= link_to (image_tag provenience.image, :class=>"itemholsIm"), provenience %>
            <p><%= provenience.description %></p>
            
            <p><a href="/provenience/<%= provenience.title %>" class="button"><%= provenience.title %></a></p>
        </div>

    <% end %>
    </div>

</div>
<div class="clear"></div>

app/views/items/_search.html.erb
<%= form_tag("/search", :method => "post") do %>
<%= label_tag(:q, "Search for:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>

app/views/items/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

 <div id="itemsContainer">
   
  
  <h1>Products</h1>
  
  
<div class="row">
  <div class="col-6 col-md-4"><%=render 'items/search'%></div>
  <div class="col-6 col-md-4">.col-6 .col-md-4</div>
  <div class="col-6 col-md-4">.col-6 .col-md-4</div>
</div>

    
    

  
  <div class="row">
  
  <div class="col-4">.col-4<br>
        <%=render 'items/categories'%>

</div>

  <div class="col-5"><br>
  
    <% @items.each do |item| %>

      <div class="itemhols">
        
        <div class="row">
  
    <div class="card border-info mb-3 ml-3 mr-3" style="width: 18rem;">
           <%= link_to (image_tag item.image_url, :class => "card-img-top"), item %>
          <div class="card-body">
            <h1 class="card-title"><%= item.title %></h1>
            <p class="card-text"><%= item.description %></p>
            <br>
                Category: <%= item.category %>
            <br>
            
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
              <label class="form-check-label" for="defaultCheck1">
                In Stock? <%= item.inStock %>
              </label>
            </div>
            
            
            
            <p class="price">Price <%= number_to_currency(item.price, :unit => "€") %>
               
                  <%#=    Brand: <%= item.brand %></p> 
               <p>
            
            <%= link_to 'Show',  item, :class => "btn btn-primary", :role => "button" %>
            
            <p>
                <button class="btn1" onclick="window.location.href='/cart/<%= item.id %>'">
                   <span class="circle" aria-hidden="true">
                   <span class="icon arrow"></span>
                   </span>
                   <span class="button-text">Add to Cart</span>
                </button>
             </p>
          </div>
            

          

          <% if user_signed_in? %> 
           <% if current_user.admin? %>
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Admin user options
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a <%= link_to "All users List", "/allusers", :class =>"dropdown-item" %></a> 
                    <a <%= link_to 'New Item',  new_item_path, :class => "dropdown-item", :role => "button" %> </a>
                    <a <%= link_to 'Edit', edit_item_path(item), :class =>"dropdown-item", :role=>"button" %></a>
                    <a <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"dropdown-item", :role=>"button" %></a>
                    <a <%= link_to 'New Category', new_category_path, :class =>"dropdown-item", :role=>"button"  %></a>
                    <a <%= link_to 'New provenience area', new_provenience_path, :class =>"dropdown-item", :role=>"button"  %></a>  
                  </div>
                </div>
          <% end %>
          <% end %>
    </div>
    
  </div>
  
</div>
        
        

        
</div>
    <% end %>
    

    
<div class="pagination"> <%= will_paginate @items, previous_label: " back ", next_label: " following ", inner_window:0, outer_window:0  %> </div>

</div>

<br>



  
  
  
  
  </div>
</div>
  
  
  
  
     
      

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<h2>You Searched Our Product Catalog For <%= @search_term %></h2>

<% if @items.length == 0  %>
<br />
<h2>No products were found to match your search</h2>
<% end %>


<table class="catalog">
  <% @items.each do |item| %>
      <tr>
        <td>
          <div class="image">
            <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
          </div>
          <div class="title">
            <%= link_to item.title, item %>
          </div>
          <div class="description">
            <%= item.description %>
          </div>  
          <div class="price">
             <%= number_to_currency(item.price, :unit => "€") %>
          </div>
          <div class="links">
            <% if user_signed_in? %>
            <a href="/cart/<%= item.id %>">Add to Cart</a>
              <%= link_to 'Edit', edit_item_path(item) %>
              <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%else%>
            
              
            <%end%>  
        </div>
        </td>
      </tr>
    <% end %>
</table>

app/views/items/show.html.erb
<div role="alert">
  <p class="alert alert-success"><%= notice %></p>
</div>

 <div id="itemsContainer">
   <h1><%= @item.title %></h1>
   <%= image_tag @item.image_url, :class => 'welcomIm'  %>
       <h2><%= @item.description %></h1>
   
    <div class="itemhols">
       <p>Price <%= number_to_currency(@item.price, :unit => "€") %>
       <br>
        Category: <%= @item.category %>
        <br>
        <%#= Brand: <%= @item.brand %></p>
       
       <p>
         <%= link_to 'Back',  items_path, :class => "button", :role => "button" %>
         <%= link_to 'Edit',  edit_item_path(@item), :class => "button", :role => "button" %>
         
       </p>
        
      </div>
   
   
   </div>